export enum TipoProducto {
    CAFE_EN_GRANOS = "CAFE_EN_GRANOS",
    FILTROS = "FILTROS",
    CAPSULAS = "CAPSULAS",
    CAFETERAS = "CAFETERAS",
    CAFE_TORRADO = "CAFE_TORRADO",
    MOLINILLOS = "MOLINILLOS",
    ACCESORIOS = "ACCESORIOS"
}