-- AlterTable
ALTER TABLE `producto` ADD COLUMN `tipoProducto` ENUM('CAFE_EN_GRANOS', 'FILTROS', 'CAPSULAS', 'CAFETERAS', 'CAFE_TORRADO', 'MOLINILLOS', 'ACCESORIOS') NOT NULL DEFAULT 'CAFE_EN_GRANOS';
